[project]
name = 'myapp'
version = '0.1.0'
requires-python = '>=3.12.2'

[project.optional-dependencies]
dev = ['pytest', 'pytest-cov', 'ruff', 'taskipy']

[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[tool.ruff]
line-length = 79
extend-exclude = ['migrations']

[tool.ruff.lint]
select = ['I','F','E','W','PL','PT']
preview = true

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.pytest.ini_options]
pythonpath = '.'
addopts ='-p no:warnings'

[tool.taskipy.tasks]
lint = 'ruff check'
pre_format = 'ruff check --fix'
format = 'ruff format'
run = 'uvicorn app.main:app --host 0.0.0.0 --reload'
pre_test = 'task lint'
test = 'pytest -s -x --cov=app -vv'
post_test = 'coverage html'